### ISSUE TITLE
Remove tutors from vc

### ISSUE THREAD

**Issue by amilajack** [TylerWasniowski/cosac-timecard-manager#1]
Generally not a good idea to store user info in version control. Should use db for this

**Comment by TylerWasniowski** [comment]
Ahhhh this is so embarrassing! This was meant to be a very small project for CoSAC.

The user data can be aquired without authentication due to how setmore and opentimeclock work.

**Comment by TylerWasniowski** [comment]
Fixed with 0f7d2afe0b059e79c0b731f257c084669bb8ec1f
